{{- if and .Values.chaos.enabled .Values.chaos.experiments.coreServicePodKill.enabled (not .Values.chaos.experiments.coreServicePodKill.schedule.enabled) }}
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: {{ include "team7-helm.fullname" . }}-core-service-pod-kill
  namespace: {{ .Values.global.namespace }}
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - {{ .Values.global.namespace }}
    labelSelectors:
      "app.kubernetes.io/component": "core-service"
  duration: {{ .Values.chaos.experiments.coreServicePodKill.duration | quote }}
{{- end }}