{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "team7-helm.fullname" . }}-migrations-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "team7-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "team7-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: {{ .Values.migrations.restartPolicy }}
      containers:
      - name: migrations
        image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
        imagePullPolicy: Always
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: POSTGRES_DATABASE
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-postgres-secrets
              key: DATABASE_URL
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-s3-secrets
              key: S3_BUCKET
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-s3-secrets
              key: S3_ENDPOINT_URL
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-s3-secrets
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "team7-helm.fullname" . }}-s3-secrets
              key: S3_SECRET_ACCESS_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
  backoffLimit: 3
{{- end }}

