{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flask-app.serviceAccountName" . }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: {{ include "flask-app.fullname" . }}
{{- end }}

