{{- if and .Values.trainService.enabled .Values.trainService.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "team7-helm.fullname" . }}-train-service-hpa
  labels:
    {{- include "team7-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: train-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "team7-helm.fullname" . }}-train-service
  minReplicas: {{ .Values.trainService.hpa.minReplicas }}
  maxReplicas: {{ .Values.kafka.topics.partitions }}
  metrics:
    {{- if .Values.trainService.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.trainService.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.trainService.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.trainService.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
{{- end }}

