{{- if and .Values.externalSecret.enabled .Values.externalSecret.s3.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "flask-app.fullname" . }}-secret-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ include "flask-app.fullname" . }}-secret-s3
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.s3.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
    {{- end }}
{{- end }}

