{{- if and .Values.kafka.enabled (eq .Values.kafka.storage.type "persistent-claim") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask-app.fullname" . }}-kafka-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.kafka.storage.size }}
  {{- if .Values.kafka.storage.class }}
  storageClassName: {{ .Values.kafka.storage.class }}
  {{- end }}
{{- end }}

