{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: plain
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: controller
  selector:
    {{- include "flask-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
{{- end }}

