apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: controller
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  roles:
    - controller
  resources:
    requests:
      memory: 512Mi
      cpu: "150m"
    limits:
      memory: 512Mi
      cpu: "200m"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: broker
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
  roles:
    - broker
  resources:
    requests:
      memory: 1Gi
      cpu: "100m"
    limits:
      memory: 1Gi
      cpu: "200m"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: my-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  # Пример настройки логирования для Kafka и операторов
  kafka:
    version: 4.1.1
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    logging:
      type: inline
      loggers:
        # Логирование Kafka (уровни: TRACE, DEBUG, INFO, WARN, ERROR)
        log4j.logger.org.apache.kafka: INFO
        log4j.logger.kafka: INFO
        log4j.logger.org.apache.zookeeper: WARN
        rootLogger.level: INFO
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          log4j.logger.operator: INFO
    userOperator: 
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
          log4j.logger.operator: INFO