{{- if .Values.kafka.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "flask-app.fullname" . }}-create-kafka-topics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flask-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-topics
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "flask-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka-topics
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topics
        image: apache/kafka:3.7.0
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        command:
        - /bin/sh
        - -c
        - |
          KAFKA_HOST="{{ include "flask-app.fullname" . }}-kafka"
          KAFKA_PORT="9092"
          BOOTSTRAP_SERVER="${KAFKA_HOST}:${KAFKA_PORT}"
          
          echo "Waiting for Kafka to be ready..."
          MAX_RETRIES=5
          RETRY_COUNT=0
          SUCCESS=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            # Пытаемся подключиться к Kafka
            if kafka-broker-api-versions.sh --bootstrap-server ${BOOTSTRAP_SERVER} > /dev/null 2>&1; then
              echo "Kafka is ready!"
              SUCCESS=1
              break
            fi
            
            # Выводим ошибку для диагностики (только каждые 5 попыток, чтобы не засорять логи)
            if [ $((RETRY_COUNT % 5)) -eq 0 ]; then
              ERROR_OUTPUT=$(kafka-broker-api-versions.sh --bootstrap-server ${BOOTSTRAP_SERVER} 2>&1 || true)
              echo "Waiting for Kafka API... ($RETRY_COUNT/$MAX_RETRIES)"
              echo "Error: ${ERROR_OUTPUT}"
            else
              echo "Waiting for Kafka API... ($RETRY_COUNT/$MAX_RETRIES)"
            fi
            
            sleep 3
            RETRY_COUNT=$((RETRY_COUNT + 1))
          done
          
          if [ $SUCCESS -eq 0 ]; then
            echo "ERROR: Kafka is not ready after $MAX_RETRIES attempts (${MAX_RETRIES} * 3 = $((MAX_RETRIES * 3)) seconds)"
            echo "Trying to get detailed error information..."
            kafka-broker-api-versions.sh --bootstrap-server ${BOOTSTRAP_SERVER} || true
            echo "Checking if service exists..."
            getent hosts ${KAFKA_HOST} || echo "Service ${KAFKA_HOST} not found in DNS"
            exit 1
          fi
          
          # Дополнительная пауза для полной инициализации KRaft метаданных
          echo "Kafka is ready, waiting additional 10 seconds for KRaft metadata initialization..."
          sleep 10
          
          echo "Creating topics..."
          kafka-topics.sh --create \
            --bootstrap-server ${BOOTSTRAP_SERVER} \
            --topic flask-app-events \
            --partitions 3 \
            --replication-factor 1 \
            --config retention.ms=86400000 \
            --config segment.bytes=1073741824 \
            --if-not-exists 2>&1
          
          TOPIC_EXIT_CODE=$?
          
          if [ $TOPIC_EXIT_CODE -eq 0 ]; then
            echo "Topic created successfully"
          else
            echo "Topic creation returned exit code: $TOPIC_EXIT_CODE"
            # Проверяем, существует ли топик (код 0 означает, что топик уже существует)
            echo "Checking if topic already exists..."
            if kafka-topics.sh --list --bootstrap-server ${BOOTSTRAP_SERVER} 2>/dev/null | grep -q "^flask-app-events$"; then
              echo "Topic 'flask-app-events' already exists, continuing..."
            else
              echo "ERROR: Topic creation failed and topic does not exist"
              exit 1
            fi
          fi
          
          echo "Verifying topic was created..."
          kafka-topics.sh --describe --bootstrap-server ${BOOTSTRAP_SERVER} --topic flask-app-events || echo "Warning: Could not describe topic"
          echo "Topics creation job completed successfully"
{{- end }}

