{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "team7-helm.fullname" . }}-zookeeper
  labels:
    {{- include "team7-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.zookeeper.service.port }}
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: {{ include "team7-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "team7-helm.fullname" . }}-zookeeper
  labels:
    {{- include "team7-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: zookeeper
spec:
  serviceName: {{ include "team7-helm.fullname" . }}-zookeeper
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "team7-helm.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "team7-helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: "{{ .Values.zookeeper.image.repository }}:{{ .Values.zookeeper.image.tag }}"
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper/data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z localhost 2181"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z localhost 2181"
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: zookeeper-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.zookeeper.persistence.storageClass }}
      storageClassName: {{ .Values.zookeeper.persistence.storageClass }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.zookeeper.persistence.size }}
{{- end }}

